/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simplecalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author adelm
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNumberText = new javax.swing.JTextField();
        secondNumberText = new javax.swing.JTextField();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        answerLabel = new javax.swing.JLabel();
        multiplyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");

        jLabel1.setText("First Number");

        jLabel2.setText("Second Number");

        firstNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberTextActionPerformed(evt);
            }
        });

        secondNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNumberTextActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.setToolTipText("Add");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        answerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerLabel.setText("The Answer is ");

        multiplyButton.setText("*");
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(firstNumberText)
                    .addComponent(secondNumberText)
                    .addComponent(answerLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusButton)
                    .addComponent(minusButton)
                    .addComponent(multiplyButton))
                .addGap(33, 33, 33)
                .addComponent(answerLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void secondNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNumberTextActionPerformed

    private void firstNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNumberTextActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        // TODO add your handling code here:
              int number1,number2;
        try {
             number1 = Integer.parseInt(this.firstNumberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad First Number", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        try {
             number2 = Integer.parseInt(this.secondNumberText.getText());
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad Second Number", "ERROR!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      int answer = number1 - number2;
      this.answerLabel.setText(
                         "The answer is: "+answer);  
    }//GEN-LAST:event_minusButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        // TODO add your handling code here:
        int number1,number2;
        try {
             number1 = Integer.parseInt(this.firstNumberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad First Number", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        try {
             number2 = Integer.parseInt(this.secondNumberText.getText());
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad Second Number", "ERROR!", JOptionPane.ERROR_MESSAGE);
            return;
        }
         Operations o1 = new Operations();
      int  answer = o1.add(number1, number2);
      this.answerLabel.setText(
                         "The answer is: "+answer);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        // TODO add your handling code here:
               int number1,number2;
        try {
             number1 = Integer.parseInt(this.firstNumberText.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad First Number", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        try {
             number2 = Integer.parseInt(this.secondNumberText.getText());
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Bad Second Number", "ERROR!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      int answer = number1 * number2;
      this.answerLabel.setText(
                         "The answer is: "+answer); 
    }//GEN-LAST:event_multiplyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new CalculatorForm().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerLabel;
    private javax.swing.JTextField firstNumberText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JTextField secondNumberText;
    // End of variables declaration//GEN-END:variables

    private int add(int number1, int number2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
